# Generated by Django 4.1.2 on 2022-11-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_cast_and_crew_remove_movie_actors_delete_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast_and_crew',
            field=models.ManyToManyField(to='movie.cast_and_crew'),
        ),
    ]
