# Generated by Django 4.1.2 on 2022-11-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_director_movie_writers_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='episodes',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
