# Generated by Django 4.1.2 on 2022-11-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast_and_crew',
            name='image',
            field=models.ImageField(null=True, upload_to='movie'),
        ),
    ]
