# Generated by Django 4.1.2 on 2022-11-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_cast_and_crew_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast_and_crew',
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_episode', to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='episodes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writers',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cast_and_Crew',
        ),
    ]
