# Generated by Django 4.1.2 on 2022-11-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_remove_movie_cast_and_crew_alter_episode_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast_and_Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('character', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='cast')),
            ],
        ),
    ]
