# Generated by Django 4.1.2 on 2022-11-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_cast_and_crew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cast_and_Crew',
        ),
    ]
