# Generated by Django 4.1.2 on 2022-11-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_cast_and_crew_movie_cast_and_crew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast_and_crew',
        ),
    ]
