# Generated by Django 4.1.2 on 2022-11-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_cast_and_crew_sub_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast_and_crew',
            name='sub_character',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
