# Generated by Django 3.2.15 on 2022-11-21 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0018_alter_cast_and_crew_sub_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(null=True, upload_to='user_profile')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE'), ('O', 'OTHERS'), ('N', 'NO INFORMATION')], default='N', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
