# Generated by Django 4.1.2 on 2022-11-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_alter_cast_and_crew_sub_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast_and_crew',
            field=models.ManyToManyField(to='movie.cast_and_crew'),
        ),
    ]
