# Generated by Django 3.2.15 on 2022-11-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0019_profile'),
        ('movie', '0020_cast_and_crew_title_movie'),
    ]

    operations = [
    ]
