# Generated by Django 3.2.15 on 2022-11-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_merge_0019_profile_0020_cast_and_crew_title_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/media/user_profile/User.jpg', null=True, upload_to='user_profile'),
        ),
    ]
