# Generated by Django 3.2.15 on 2022-11-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0025_auto_20221126_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=' ', null=True, upload_to='user_profile'),
        ),
    ]
