# Generated by Django 4.1.2 on 2022-11-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0028_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RA', 'RECENTLY ADDED'), ('MW', 'MOST WATCHED'), ('TR', 'TOP RATED'), ('T', 'TRENDING'), ('U', 'UPCOMING')], max_length=2, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.AlterModelOptions(
            name='cast_and_crew',
            options={'verbose_name': 'Cast and Crew', 'verbose_name_plural': 'Casts and Crews'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='episodes',
        ),
        migrations.AddField(
            model_name='episode',
            name='video',
            field=models.FileField(null=True, upload_to='episodes'),
        ),
        migrations.AddField(
            model_name='movie',
            name='format',
            field=models.CharField(choices=[('TV', 'TV SERIES'), ('PS', 'POPULAR MOVIES ON SEPTEMBER'), ('F', 'FEATURE')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='national',
            field=models.CharField(choices=[('Argentina', 'ARGENTINA'), ('Australia', 'AUSTRALIA'), ('Belgium', 'BELGIUM'), ('Brazil', 'BRAZIL'), ('Canada', 'CANADA'), ('China', 'CHINA'), ('USA', 'USA'), ('Vietnamese', 'VIETNAMESE')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='time',
            field=models.CharField(default='2h10m', max_length=6),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(null=True, upload_to='trailers'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_image',
            field=models.ImageField(null=True, upload_to='trailer_image'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trivia_image',
            field=models.ImageField(null=True, upload_to='trivia'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trivia_summary',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='trivia_url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cast_and_crew',
            name='image',
            field=models.ImageField(default='/cast/noimage.jpg', upload_to='cast'),
        ),
        migrations.AlterField(
            model_name='cast_and_crew',
            name='sub_character',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast_and_crew',
            field=models.ManyToManyField(related_name='cast_crew', to='movie.cast_and_crew'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='status',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Action', 'ACTION'), ('Drama', 'DRAMA'), ('Comedy', 'COMEDY'), ('Romance', 'ROMANCE'), ('Adventure', 'ADVENTURE'), ('Documentary', 'DOCUMENTARY'), ('Family', 'FAMILY'), ('Historical', 'HISTORICAL'), ('Musical', 'MUSICAL'), ('Horror', 'HORROR'), ('Science fiction', 'SCIENCE FICTION'), ('Tragedy', 'TRAGEDY'), ('War', 'WAR'), ('Westerns', 'WESTERNS')], max_length=15, unique=True)),
                ('movie', models.ManyToManyField(related_name='movie_category', to='movie.movie')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.ManyToManyField(to='movie.statuses', verbose_name='status'),
        ),
    ]
