# Generated by Django 3.2.15 on 2022-11-26 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0034_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='comnent_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
