# Generated by Django 3.2.15 on 2022-11-27 00:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0035_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='unlikes',
            field=models.ManyToManyField(related_name='comnent_unlike', to=settings.AUTH_USER_MODEL),
        ),
    ]
