# Generated by Django 3.2.15 on 2022-11-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0036_comment_unlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='who_has_it_open',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
