# Generated by Django 3.2.15 on 2022-11-27 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0038_comment_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='loves',
            field=models.ManyToManyField(related_name='movie_love', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='marks',
            field=models.ManyToManyField(related_name='movie_mark', to=settings.AUTH_USER_MODEL),
        ),
    ]
