# Generated by Django 3.2.15 on 2022-11-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0039_auto_20221128_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='who_has_it_open',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
