# Generated by Django 3.2.15 on 2022-11-27 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0040_movie_who_has_it_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='loves',
            field=models.ManyToManyField(related_name='movie_love', to=settings.AUTH_USER_MODEL, verbose_name='loves'),
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.ImageField(blank=True, default=0, null=True, upload_to='')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
