# Generated by Django 3.2.15 on 2022-11-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0041_auto_20221128_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingstar',
            name='rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
