# Generated by Django 4.1.2 on 2022-11-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0043_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_video',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
