# Generated by Django 4.1.2 on 2022-11-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0044_episode_episode_movie_trailer_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='video',
        ),
    ]
