# Generated by Django 3.2.15 on 2022-11-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0044_episode_ep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='number_episode',
        ),
    ]
