# Generated by Django 3.2.15 on 2022-11-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0045_remove_episode_number_episode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='Ep',
        ),
        migrations.AddField(
            model_name='episode',
            name='number_episode',
            field=models.IntegerField(default=1),
        ),
    ]
