# Generated by Django 4.1.2 on 2022-11-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0045_remove_episode_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer',
        ),
    ]
