# Generated by Django 4.1.2 on 2022-11-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0047_remove_category_movie_movie_categogies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='categogies',
            new_name='categories',
        ),
    ]
