# Generated by Django 3.2.15 on 2022-11-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0046_auto_20221129_0041'),
        ('movie', '0048_rename_categogies_movie_categories'),
    ]

    operations = [
    ]
