# Generated by Django 3.2.15 on 2022-11-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0051_movie_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_need_to_notify',
            field=models.BooleanField(default=False),
        ),
    ]
