# Generated by Django 3.2.15 on 2022-11-29 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0052_profile_is_need_to_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='history',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='loves',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_love', to=settings.AUTH_USER_MODEL, verbose_name='loves'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='marks',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_mark', to=settings.AUTH_USER_MODEL),
        ),
    ]
