# Generated by Django 3.2.15 on 2022-11-29 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0054_movie_sorts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='sorts',
        ),
    ]
