# Generated by Django 4.1.3 on 2022-12-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0055_remove_movie_sorts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer_image',
        ),
    ]
