# Generated by Django 3.2.16 on 2022-12-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0056_remove_movie_trailer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='child',
            field=models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=10, null=True),
        ),
    ]
