# Generated by Django 4.1.2 on 2022-12-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0056_remove_movie_trailer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='sort',
            field=models.CharField(choices=[('Newest', 'NEWEST'), ('Most view', 'MOST VIEW'), ('New update', 'NEW UPDATE')], default='Newest', max_length=20),
        ),
    ]
