# Generated by Django 4.1.2 on 2022-12-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0057_movie_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='condition',
            field=models.CharField(choices=[('Trailer', 'TRAILER'), ('Now showing', 'NOW SHOWING'), ('Finish', 'FINISH')], max_length=20, null=True),
        ),
    ]
