# Generated by Django 4.1.2 on 2022-12-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0057_comment_reply'),
        ('movie', '0058_movie_condition'),
    ]

    operations = [
    ]
