# Generated by Django 4.1.2 on 2022-12-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0057_movie_child'),
        ('movie', '0059_merge_0057_comment_reply_0058_movie_condition'),
    ]

    operations = [
    ]
