# Generated by Django 3.2.15 on 2022-12-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0060_merge_20221204_0124'),
        ('movie', '0060_merge_20221204_0159'),
    ]

    operations = [
    ]
