# Generated by Django 4.1.2 on 2022-12-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0060_merge_20221202_2112'),
        ('movie', '0061_merge_20221204_0225'),
        ('movie', '0061_merge_20221204_0300'),
    ]

    operations = [
    ]
