# Generated by Django 3.2.15 on 2022-12-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0061_merge_20221204_0225'),
        ('movie', '0061_merge_20221204_0300'),
    ]

    operations = [
    ]
