# Generated by Django 3.2.15 on 2022-12-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0060_merge_20221202_2112'),
        ('movie', '0062_merge_20221204_0320'),
    ]

    operations = [
    ]
