# Generated by Django 4.1.3 on 2022-12-04 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0062_merge_20221204_2303'),
        ('movie', '0063_merge_20221204_2001'),
    ]

    operations = [
    ]
